-- 1. Adicionar coluna locale com default pt-BR e CHECK constraint
ALTER TABLE public.legal_documents
  ADD COLUMN locale TEXT NOT NULL DEFAULT 'pt-BR'
  CHECK (locale IN ('pt-BR', 'en'));

-- 2. Substituir UNIQUE (doc_type, version) por UNIQUE (doc_type, locale, version)
ALTER TABLE public.legal_documents
  DROP CONSTRAINT legal_documents_doc_type_version_key;

ALTER TABLE public.legal_documents
  ADD CONSTRAINT legal_documents_doc_type_locale_version_key
  UNIQUE (doc_type, locale, version);

-- 3. Substituir índice por composto incluindo locale
DROP INDEX IF EXISTS idx_legal_documents_type_version;
CREATE INDEX idx_legal_documents_type_locale_version
  ON public.legal_documents (doc_type, locale, version DESC);

-- 4. Seed Terms of Use v1 em inglês
INSERT INTO public.legal_documents (doc_type, version, locale, content) VALUES (
  'terms',
  1,
  'en',
  E'# Terms of Use\n\n_Last updated: publication date._\n\n> **Notice:** This text is an initial template and should be reviewed by a legal professional before production use.\n\n## 1. Acceptance of Terms\n\nBy creating an account or using the NEVVOH platform ("Service"), you ("User") fully agree to these Terms of Use. If you do not agree, do not use the Service.\n\n## 2. Service Description\n\nNEVVOH is a SaaS platform for managing tasks, teams, meetings, ideas, and knowledge, offered under a monthly per-seat subscription.\n\n## 3. Registration and Account\n\n- The User must provide truthful, complete, and up-to-date information.\n- The User is responsible for keeping their password confidential and for all activities performed under their account.\n- Accounts may be suspended in cases of misuse, fraud, or non-payment.\n\n## 4. Subscription and Payment\n\n- The Service is billed per seat (active user), with a minimum of 10 seats per administrator.\n- Free trial period of 14 days, no credit card required.\n- After the trial, continued use requires an active subscription.\n- Payment delays may result in suspension of access.\n\n## 5. Acceptable Use\n\nThe following are prohibited:\n- Using the Service for unlawful purposes.\n- Attempting to access other users'' data without authorization.\n- Performing reverse engineering, scraping, or attacks against the Service.\n- Submitting offensive, defamatory content or content that infringes third-party rights.\n\n## 6. Intellectual Property\n\n- The NEVVOH software, brand, design, and content are the exclusive property of the company.\n- Content generated by the User (tasks, attachments, ideas, etc.) remains their property. The User grants the platform a limited license to store and process such content as necessary for providing the Service.\n\n## 7. Limitation of Liability\n\nThe Service is provided "as is". The company is not liable for:\n- Data loss arising from improper use.\n- Outages caused by events beyond its control.\n- Lost profits or indirect damages.\n\n## 8. Cancellation\n\nThe User may cancel their subscription at any time. Access remains active until the end of the period already paid for. There are no prorated refunds.\n\n## 9. Changes to the Terms\n\nThe company may update these Terms at any time. Material changes will be communicated by email or on the platform.\n\n## 10. Jurisdiction\n\nThe courts of the company''s headquarters jurisdiction are elected to resolve any matters arising from these Terms.\n\n---\n\nQuestions? Contact us via the platform support.'
);

-- 5. Seed Privacy Policy v1 em inglês
INSERT INTO public.legal_documents (doc_type, version, locale, content) VALUES (
  'privacy',
  1,
  'en',
  E'# Privacy Policy\n\n_Last updated: publication date._\n\n> **Notice:** This text is an initial template and should be reviewed by a legal professional before production use, especially for GDPR/LGPD compliance.\n\n## 1. Data Controller\n\nNEVVOH is the controller of personal data collected through the platform, in accordance with applicable data protection laws.\n\n## 2. Data Collected\n\n**Data provided by the User:**\n- Name, email, password (stored as a hash).\n- Tax data (for paying customers): tax ID, legal name, address.\n- Generated content: tasks, comments, attachments, ideas, meeting minutes.\n\n**Data collected automatically:**\n- IP address, browser type, operating system.\n- Platform access and usage logs.\n- Essential cookies for authentication.\n\n## 3. Purpose of Processing\n\nWe use your data to:\n- Deliver the contracted Service.\n- Authenticate and secure your account.\n- Issue invoices and process billing.\n- Send operational and commercial notifications (the latter with consent).\n- Comply with legal obligations.\n\n## 4. Legal Basis\n\n- **Contract performance**: for most platform features.\n- **Consent**: for marketing communications.\n- **Legal obligation**: for retention of tax data.\n- **Legitimate interest**: for security and fraud prevention.\n\n## 5. Sharing\n\nWe do not sell personal data. We share only with:\n- Infrastructure providers (hosting, transactional email) under confidentiality agreements.\n- Authorities, when required by law.\n\n## 6. Storage and Security\n\n- Data is stored on cloud servers with encryption in transit (HTTPS) and at rest.\n- We apply role-based access control (RLS) and tenant isolation between customers.\n- Daily automatic backups.\n\n## 7. Retention\n\n- Account data: while the account is active.\n- Tax data: for the period required by tax legislation (minimum 5 years).\n- Audit logs: up to 24 months.\n- After cancellation, data may be anonymized or deleted upon request, respecting legal obligations.\n\n## 8. Data Subject Rights\n\nAt any time, you may:\n- Confirm the existence of processing of your data.\n- Access, correct, or request deletion of your data.\n- Withdraw consents.\n- Request portability.\n- File a complaint with the relevant data protection authority.\n\nTo exercise your rights, contact us via support or the email below.\n\n## 9. Cookies\n\nWe only use essential cookies for the operation of the platform (authentication). We do not use third-party tracking cookies without explicit consent.\n\n## 10. Data Protection Officer (DPO)\n\nFor data protection matters, contact us via the platform support channel.\n\n## 11. Changes to this Policy\n\nWe may update this Policy periodically. Material changes will be communicated by email or on the platform.\n\n---\n\nLast review: initial version.'
);